# Generated by Django 3.2.13 on 2022-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
